{{
  config(
    materialized= 'table'
  )
}}

SELECT distinct
ReasonCode,
Case
When ReasonCode = 'AUD' Then 'Audit external'
When ReasonCode = 'AID' Then 'Arrived in damage'
When ReasonCode = 'BCK' Then 'Bercak'
When ReasonCode = 'BIT' Then 'Broken In Transit'
When ReasonCode = 'BLC' Then 'Balancing'
When ReasonCode = 'CAP' Then 'Production Capacity'
When ReasonCode = 'CBR' Then 'CBR'
When ReasonCode = 'CES' Then 'Controller Emitting Smoke'
When ReasonCode = 'CNI' Then 'Incomplete component'
When ReasonCode = 'CNW' Then 'Controller does not working properly'
When ReasonCode = 'CRM' Then 'Color Mismatch'
When ReasonCode = 'CSI' Then 'Correction Stock Inventory'
When ReasonCode = 'CSO' Then 'Correction Stock Opname'
When ReasonCode = 'CSP' Then 'Correction Stock Production'
When ReasonCode = 'CST' Then 'Cost Customer'
When ReasonCode = 'CUS' Then 'Material to Customer'
When ReasonCode = 'DAM' Then 'Damaged'
When ReasonCode = 'DAP' Then 'Damaged Product'
When ReasonCode = 'DIT' Then 'Damaged In Transit'
When ReasonCode = 'DPS' Then 'Inventory Dispossal'
When ReasonCode = 'EXT' Then 'Extra From Vendor'
When ReasonCode = 'FFM' Then 'Free for Mass Production'
When ReasonCode = 'GTI' Then 'Less glass tube quantity'
When ReasonCode = 'HOL' Then 'HOLD'
When ReasonCode = 'INN' Then 'Item No Longer Needed By Customer'
When ReasonCode = 'INS' Then 'Inspection Center'
When ReasonCode = 'IT' Then 'Correction Stock IT'
When ReasonCode = 'KNF' Then 'Correction Stock Pisau Plong'
When ReasonCode = 'KRP' Then 'Keriput'
When ReasonCode = 'LPT' Then 'Terlipat'
When ReasonCode = 'MAR' Then 'Material Rejection'
When ReasonCode = 'MMI' Then 'Miscellaneous Material Issue'
When ReasonCode = 'MMK' Then 'Maintenance Machine & Equipment (KB)'
When ReasonCode = 'MMR' Then 'Miscellaneous Material Receipt'
When ReasonCode = 'MNW' Then 'Machine base does not working properly'
When ReasonCode = 'OMA' Then 'Obsolete Material'
When ReasonCode = 'OSM' Then 'Obsolete/Slow-Moving'
When ReasonCode = 'OSP' Then 'Over-Shipment of Product'
When ReasonCode = 'OVS' Then 'Over-Shipment of Product'
When ReasonCode = 'PES' Then 'Production Equipment & Supplies'
When ReasonCode = 'PIA' Then 'Physical Inventory'
When ReasonCode = 'PMQ' Then 'Poor Material Quality'
When ReasonCode = 'PMT' Then 'Promotion & Marketing'
When ReasonCode = 'PP1' Then 'Pisau Plong Bijou / Pixie'
When ReasonCode = 'PPQ' Then 'Poor Print Quality'
When ReasonCode = 'PRC' Then 'Price'
When ReasonCode = 'PVQ' Then 'Poor Vendor Quality'
When ReasonCode = 'QUA' Then 'Quality Assurance'
When ReasonCode = 'R&D' Then 'Research and Development'
When ReasonCode = 'RBK' Then 'Robek'
When ReasonCode = 'RCN' Then 'Return to Vendor (Credit Note)'
When ReasonCode = 'REF' Then 'Referral'
When ReasonCode = 'REP' Then 'Reputation'
When ReasonCode = 'RIE' Then 'Received In Error'
When ReasonCode = 'RJC' Then 'Reject production'
When ReasonCode = 'RSI' Then 'Receipt of Non Stocked Item'
When ReasonCode = 'RTS' Then 'Return to Stock'
When ReasonCode = 'RTV' Then 'Return to Vendor'
When ReasonCode = 'SAM' Then 'Sample'
When ReasonCode = 'SOD' Then 'Stock Count Inventory'
When ReasonCode = 'STC' Then 'Sticker'
When ReasonCode = 'TAP' Then 'Temporary Adjustment Production'
When ReasonCode = 'TCH' Then 'Technical Adjustment'
When ReasonCode = 'TES' Then 'Testing'
When ReasonCode = 'TRN' Then 'Training'
When ReasonCode = 'UKR' Then 'Salah Ukuran'
When ReasonCode = 'USE' Then 'Pemakaian Sundry'
When ReasonCode = 'VER' Then 'Version change'
When ReasonCode = 'WEA' Then 'Weather Damage'
When ReasonCode = 'WIS' Then 'Wrong Item Shipped'
When ReasonCode = 'WRG' Then 'Wrong Product Shipped'
When ReasonCode = 'WRI' Then 'Wrong Input'
When ReasonCode = 'ZC' Then 'Zero Cost'
Else 'Notidentify'
End AS ReasonDescription
FROM {{ source('mp_infor', 'reasoncode_MP') }} 