version: 2

sources:
  - name: mp_infor 
    database: mitraprodin-data-warehouse 
    description: Data from Infor ERP
    tables:
      - name: mp80_incentives
      - name: job_transaction_mp
      - name: META_EmployeeHalfDay_v 
      - name: JobExclude
      - name: Jobs
      - name: cost_of_production_mp_new
      - name: cost_of_production_mpkb_new
      - name: cost_of_production_jmbr_new
      - name: material_usage_mp_new
      - name: material_usage_mpkb_new
      - name: material_usage_jmbr_new
      - name: cost_of_production_PLN_mp
      - name: cost_of_production_PLN_mpkb
      - name: cost_of_production_PLN_jmbr 
      - name: salestransaction
      - name: employee_absence
      - name: user_case
      - name: hris_user
      - name: product_codes_BQ
      - name: user_absence
      - name: WorkingDays
      - name: userleave_detail
      - name: UserResign
      - name: items
      - name: item_attribute_all
      - name: jobRoutes

  - name: PlantControlGianyarDps
    database: mitraprodin-data-warehouse
    tables:
      - name: JO_PostedBy