version: 2

sources:
  - name: mp_infor 
    database: mitraprodin-data-warehouse 
    description: Data from Infor ERP
    tables:
      - name: budget_actual
      - name: budget_departement
      - name: Budget Sales Qty
      - name: budget_sales
      - name: budget_cogs
      - name: COA
      - name: COItems
      - name: cost_of_production
      - name: cost_of_production_mp_new
      - name: cost_of_production_mpkb
      - name: cost_of_production_mpkb_new
      - name: cost_of_production_jmbr
      - name: cost_of_production_jmbr_new
      - name: cost_of_production_PLN_mp
      - name: cost_of_production_PLN_mpkb
      - name: cost_of_production_PLN_jmbr
      - name: customer_data
      - name: current_material
      - name: current_material_jembrana 
      - name: current_operation
      - name: document_object 
      - name: DownTimeList
      - name: EmployeeContractHistory
      - name: employee_absence
      - name: fix_assets
      - name: fix_assets_note
      - name: GRNLines
      - name: hrpayroll_p_daily_production_summary
      - name: hrpayroll_m_section
      - name: hrpayroll_m_floor
      - name: hris_user
      - name: HRIS_CandidatePosition
      - name: HRIS_CandidateRecRequest
      - name: HRIS_McuAll
      - name: HRIS_Mcu
      - name: HRIS_Section
      - name: Infor_User
      - name: Infor_UserGroup
      - name: Infor_UserAuth
      - name: InternshipPerformance
      - name: items
      - name: items_mpkb
      - name: itemsCustomer
      - name: items_new
      - name: item_atrribute
      - name: item_attribute_all
      - name: itemsAttribute_jembrana
      - name: items_jembrana
      - name: jobRoutes
      - name: job_transaction_mp
      - name: job_transaction_mpkb
      - name: job_transaction_jmbr
      - name: JobExclude
      - name: Jobs
      - name: ledger
      - name: ledger_mpkb
      - name: ledger_notes
      - name: ledger_notes_mpkb
      - name: Labor_Exces
      - name: ListUnprocessed
      - name: ListUserContract
      - name: m_department
      - name: m_vendor
      - name: m_shipment
      - name: material_tran_jmbr
      - name: material_tran_acct
      - name: material_tran_desc
      - name: material_tran_acct_mpkb
      - name: material_tran_desc_mpkb
      - name: material_transaction
      - name: material_tran_1
      - name: material_tran_1_mpkb
      - name: material_usage
      - name: material_usage_mp_fix
      - name: material_usage_mp_new
      - name: material_usage_mpkb
      - name: material_usage_mpkb_new
      - name: material_usage_jmbr
      - name: material_usage_jmbr_new
      - name: material_transaction_coop
      - name: material_transaction_reasoncode_jmbr
      - name: material_transaction_reasoncode_mpkb
      - name: material_transaction_reasoncode_mp
      - name: META_EmployeeHalfDay_v
      - name: miradore_asset_number
      - name: miradore_devices
      - name: movement_location_mp
      - name: movement_location_mpkb
      - name: movement_location_jmbr
      - name: movement_qty_mp
      - name: movement_value_mp_new
      - name: movement_value_mpkb_new
      - name: movement_value_jmbr_new
      - name: mp123_scraps
      - name: MP34_SalesTransaction
      - name: MP76_PI_Payment
      - name: mp80_incentives
      - name: mp83_joborder_progress
      - name: mp83_joborder_progress_jemb
      - name: mp131_stock_co
      - name: mp131_stock_all_located
      - name: outstanding_co
      - name: Output_standart_new
      - name: product_codes_BQ
      - name: product_codes_mpkb
      - name: product_codes_jembrana
      - name: PR_NonInventory
      - name: pr_header
      - name: PR_Items
      - name: pr_detail
      - name: PRPO_NotesDetail
      - name: PO_Items
      - name: po_header
      - name: po_detail
      - name: PO_Receipt
      - name: PO_NonInventory
      - name: reasoncode_MP
      - name: ReqPayHeader
      - name: ReqPayDetail
      - name: RmaItems
      - name: saldo_awal_qty_mp_bq
      - name: saldo_awal_qty_mpkb_bq
      - name: salestransaction
      - name: shipment_or_fi_detail
      - name: StandartCost
      - name: standard_cost 
      - name: standard_cost_jmbr 
      - name: standard_cost_mpkb      
      - name: transtype_MP
      - name: transtype_MPKB
      - name: TurnOverMagang
      - name: user_case
      - name: user_absence
      - name: UserHistoryEmployeeStatus
      - name: userleave_detail
      - name: UserResign
      - name: uom_conversion
      - name: WorkCenter
      - name: WorkingDays  
      - name: vendorEvaluation
      - name: vendorContract  
      - name: vendorContractPrice      

  - name: PlantControlGianyarDps
    database: mitraprodin-data-warehouse
    tables:
      - name: JO_PostedBy